[tool.poetry]
name = "qr-code-generator-api"
version = "0.1.0"
description = "Based on the information gathered from the interviews, the task involves creating an endpoint that fulfills the following requirements: - Accepts input data which can vary from URLs, text, contact information, etc. This signifies the endpoint needs to be flexible enough to encode different types of data into a QR code. - Generates a QR code image from the input data. This process will involve converting the supplied data into a format that can be encoded into a QR code image. - Allows for customization of the generated QR code. This includes adjustments to the size, color, and error correction level. Each of these customizations serves a purpose; size ensures the QR code fits within various designs, color alignment with brand guidelines, and error correction level for maintaining scannability under damage or obstruction. - Returns the QR code image in a specified format as requested by the user, for example in SVG format. This demands the system to be capable of generating and providing the QR code in multiple image formats to meet diverse user preferences or requirements. The tech stack selected for implementing this solution includes Python as the programming language, FastAPI for the API framework, PostgreSQL for the database, and Prisma as the ORM. This stack is suitable for creating a performant, scalable, and maintainable application capable of handling the specified functionalities efficiently."
authors = ["AutoGPT <info@agpt.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
fastapi = "*"
prisma = "*"
pydantic = "*"
uvicorn = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
